### PR TITLE
Use composer installers for proper installation via composer

### PR DESCRIPTION
**Pull request by iMattPro**

### CODE REVIEW

**Comment by JoshyPHP** [comment]
I don't know what `composer/installers` is, how does it change the release workflow or the extension's installation?

**Comment by iMattPro** [comment]
It basically make's sure an extension gets installed into phpBB's ext folder, instead of the vendor folder, when the extension is installed through composer (and is defined as a required dependency in phpBB's composer.json)

Here's their code:
https://github.com/composer/installers/blob/master/src/Composer/Installers/PhpBBInstaller.php

It doesn't change the release workflow at all.

Basically, I want this extension to be used on phpbb.com. So we would add it to our phpBB forum's composer.json require section, so it will be installed and updated whenever we deploy updates to phpbb.com

Adding this line is also something we at phpBB recommend all extensions do anyways, to allow composer based auto installs coming in the future (3.3)

**Comment by JoshyPHP** [comment]
Ok, we're almost there. Currently the package's name is `s9e/phpbb-ext-highlighter` so it installs into `phpBB/ext/s9e/phpbb-ext-highlighter`. Is there a way to make it install to `phpBB/ext/s9e/highlighter`? Maybe an option in the `extra` part of `composer.json`? If not, it would make sense for the installer to remove the `phpbb-ext-` prefix from package name since it's becoming the convention for extensions.

**Comment by iMattPro** [comment]
well, technically, in your composer it should be named `s9e/highlighter`

Hyphens and underscores are not allowed by phpbb

**Comment by JoshyPHP** [comment]
The name isn't for the extension, it's for the package to avoid name collisions. That's how I can have a `flarum-ext-mediaembed` and `phpbb-ext-mediaembed`.

I'm trying out the `installer-name` field in `extra`. I'm 99% sure it's the way to go, trying to install as I'm typing this.

**Comment by iMattPro** [comment]
The folder structure must match the extension name set in composer. These here are the rules phpBB uses:

https://area51.phpbb.com/docs/dev/31x/extensions/tutorial_basics.html#extension-folder

**Comment by iMattPro** [comment]
You could probably leave the name as is...phpbb-ext-highlighter.

That just means that will be the name of it's package folder when it installs, which is fine so long as it matches the name in composer.

**Comment by JoshyPHP** [comment]
If they can't be namespaced, phpBB extensions will interfere with other similarly named extensions and libraries. It seems that using the name in `extra` (maybe `installer-name` I guess?) is the correct way to handle it.

**Comment by iMattPro** [comment]
no because then you're mismatching things between the extensions name and the structure.

it should be fine as is. unless you want it validated in which case the hyphens will not be allowed.

**Comment by iMattPro** [comment]
based on the name you gave it in composer, `phpBB/ext/s9e/phpbb-ext-highlighter` is the correct install location and structure.

**Comment by JoshyPHP** [comment]
Ok, so here's my take on the situation:

 - `composer/installers`'s purpose is to install extensions via Composer.
 - Package names must be unique, therefore it is a good practice to prepend extension names with the name of the software they are for.
 - `phpbbexthighlighter` is ugly as hell.
 - If I set `"extra":{"installer-name": "highlighter"}` in composer.json, the extension is installed in `ext/s9e/highligher`

I believe the correct way to resolve this issue is to support the use of `installer-name` (and possibly `installer-paths`?) in `phpbb\extension\metadata_manager::validate_dir()` and `phpbb\extension\metadata_manager::validate()`.

**Comment by iMattPro** [comment]
Well, prepending extensions names is not an issue for the most part. Your vendor name is your namespace, if you will. And the extnames are your extensions. `flarum-ext-mediaembed` would never be installed in phpBB, right? So the two should never meet, except in packagist.

By the way, i have been confused because you've been changing your composer file while we've discussed this.

`"extra":{"installer-name": "highlighter"}` is a problem, because that only names it properly if people install it through composer. What about people who download it directly from your repo, and they have to name the directories themselves? They usually go by the name in composer. So you could have people with different packaging.

Ultimately this is a simple ext with no PHP, but namespacing is an isue, which is why the package must match the name.

I'd just pick a name that works for you and go with that. Some perfectly legal names by phpbb standards:
`phpbbHighlighter`
`PhpbbExtHighlighter`
`phpbbhighlighter`

**Comment by iMattPro** [comment]
If you dont' plan to have this validated by phpBB, you can keep the hyphens in the name too. 

For example: https://packagist.org/packages/marc1706/phpbb-text-shortener

**Comment by JoshyPHP** [comment]
I have reverted the package name to `s9e/highlighter` because phpBB wouldn't install it otherwise. The package can still be installed via `composer require s9e/phpbb-ext-highlighter` although I'm not quite sure why.

**Comment by iMattPro** [comment]
It won't install it because of the hyphens

**Comment by iMattPro** [comment]
Is this not on packagist.com? I can't find it.

**Comment by iMattPro** [comment]
Oh I see. It still is on packagist, but under the original package name of `s9e/phpbb-ext-highlighter`

Apparently the name on packagist does not update. The only way to make the packagist name match the updated composer name is to mark it as Abandoned on packagist, then resubmit it to packagist anew. Any download stats from the abandoned version will be lost, if that matters.

It's up to you if you care about resubmitting it so the packagist name matches the new composer name.

**Comment by JoshyPHP** [comment]
I think the correct, long-term solution is to support [custom install names](https://github.com/composer/installers#custom-install-names) in the phpBB installer.

**Pull request merged**
